#### general settings
name: ir-sde
use_tb_logger: true
model: denoising
distortion: derain
gpu_ids: [0]

sde:
  max_sigma: 30
  T: 400
  schedule: cosine
  eps: 0.005

degradation:
  mask_root: /home/610-wws/Impainting/dataset/裁剪的图片/train/output_masks

#### 第一阶段配置
debug_mode: true
debug_dir: debug_logs

lut:
  lut_path: assets/pigment_lut33.npz
  stage1:
    inpaint_backend: auto
    inpaint_method: telea
    inpaint_radius: 3
    large_mask_ratio: 0.30
    large_mask_downsample: 0.5
    alpha: 0.7
    beta: 0.3
    inpaint_base_conf: 0.15
    inpaint_decay_strength: 1.0


#### datasets
datasets:
  train:
    name: Train_Dataset
    mode: GT
    dataroot_GT: /home/610-wws/Impainting/dataset/裁剪的图片/train/cropped_images

    use_shuffle: true
    n_workers: 8
    batch_size: 16
    GT_size: 256
    use_flip: true
    use_rot: true
    color: RGB


#### network structures
network_G:
  # which_model_G: ConditionalUNet
  # setting:
  #   in_nc: 3
  #   out_nc: 3
  #   nf: 64
  #   depth: 4
  which_model_G: ConditionalUNetWithBrush
  setting:
    in_nc: 3
    out_nc: 3
    nf: 64
    depth: 4
    guide_dim: 64
    use_conf_gate: true
    brush_setting:
      in_nc: 8
      nf: 64
      depth: 4

#### path
path:
  pretrain_model_G: /home/610-wws/Impainting/StrDiffusion+e00/train/texture/config/inpainting/log/ir-sde/models/best_G.pth
  strict_load: false
  resume_state: ~

#### training settings: learning rate scheme, loss
train:
  optimizer: Adam
  lr_G: !!float 1e-4
  lr_scheme: MultiStepLR
  beta1: 0.9
  beta2: 0.999
  niter: 150000
  warmup_iter: 5000
  lr_steps: [40000, 80000, 110000]
  lr_gamma: 0.5
  eta_min: !!float 1e-7

  # criterion
  is_weighted: False
  loss_type: l1
  weight: 1.0

  manual_seed: 0

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: 5000
  use_tb_logger: true
